# Generated by Django 4.2 on 2023-04-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductLink',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
