# Generated by Django 4.2 on 2023-04-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_productlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdInfo', models.CharField(max_length=255)),
                ('ErrorDetail', models.CharField(max_length=255)),
            ],
        ),
    ]
