# Generated by Django 4.1.2 on 2023-04-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='NormalPrice',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SalePrice',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('ProdID', 'FeatureName')},
        ),
    ]
